//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sticky_Ghost.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialLocation {
            get {
                return ((string)(this["InitialLocation"]));
            }
            set {
                this["InitialLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 100")]
        public global::System.Drawing.Color myColor {
            get {
                return ((global::System.Drawing.Color)(this["myColor"]));
            }
            set {
                this["myColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool formTop {
            get {
                return ((bool)(this["formTop"]));
            }
            set {
                this["formTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textName {
            get {
                return ((string)(this["textName"]));
            }
            set {
                this["textName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int autosave_Property {
            get {
                return ((int)(this["autosave_Property"]));
            }
            set {
                this["autosave_Property"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool savefile_Property {
            get {
                return ((bool)(this["savefile_Property"]));
            }
            set {
                this["savefile_Property"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI Semibold, 11.25pt, style=Bold")]
        public global::System.Drawing.Font currentfont {
            get {
                return ((global::System.Drawing.Font)(this["currentfont"]));
            }
            set {
                this["currentfont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("410")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 40, 40")]
        public global::System.Drawing.Color PanelNavbarTheme {
            get {
                return ((global::System.Drawing.Color)(this["PanelNavbarTheme"]));
            }
            set {
                this["PanelNavbarTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37, 37, 36")]
        public global::System.Drawing.Color Main {
            get {
                return ((global::System.Drawing.Color)(this["Main"]));
            }
            set {
                this["Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37, 37, 36")]
        public global::System.Drawing.Color TextColor {
            get {
                return ((global::System.Drawing.Color)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 46")]
        public global::System.Drawing.Color NavbarLineColor {
            get {
                return ((global::System.Drawing.Color)(this["NavbarLineColor"]));
            }
            set {
                this["NavbarLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44, 44, 43")]
        public global::System.Drawing.Color WDBorder1Color {
            get {
                return ((global::System.Drawing.Color)(this["WDBorder1Color"]));
            }
            set {
                this["WDBorder1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44, 44, 43")]
        public global::System.Drawing.Color WDBorder2Color {
            get {
                return ((global::System.Drawing.Color)(this["WDBorder2Color"]));
            }
            set {
                this["WDBorder2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44, 44, 43")]
        public global::System.Drawing.Color WDBorder3Color {
            get {
                return ((global::System.Drawing.Color)(this["WDBorder3Color"]));
            }
            set {
                this["WDBorder3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44, 44, 43")]
        public global::System.Drawing.Color NavbarSideline1Color {
            get {
                return ((global::System.Drawing.Color)(this["NavbarSideline1Color"]));
            }
            set {
                this["NavbarSideline1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44, 44, 43")]
        public global::System.Drawing.Color NavbarSideline2Color {
            get {
                return ((global::System.Drawing.Color)(this["NavbarSideline2Color"]));
            }
            set {
                this["NavbarSideline2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 40, 40")]
        public global::System.Drawing.Color BtnMinimize_BC {
            get {
                return ((global::System.Drawing.Color)(this["BtnMinimize_BC"]));
            }
            set {
                this["BtnMinimize_BC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 40, 40")]
        public global::System.Drawing.Color BtnMinimize_ILC {
            get {
                return ((global::System.Drawing.Color)(this["BtnMinimize_ILC"]));
            }
            set {
                this["BtnMinimize_ILC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59, 59, 59")]
        public global::System.Drawing.Color BtnMinimize_IFC {
            get {
                return ((global::System.Drawing.Color)(this["BtnMinimize_IFC"]));
            }
            set {
                this["BtnMinimize_IFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24, 100, 38")]
        public global::System.Drawing.Color BtnMinimize_ALC {
            get {
                return ((global::System.Drawing.Color)(this["BtnMinimize_ALC"]));
            }
            set {
                this["BtnMinimize_ALC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 40, 40")]
        public global::System.Drawing.Color BtnClose_BC {
            get {
                return ((global::System.Drawing.Color)(this["BtnClose_BC"]));
            }
            set {
                this["BtnClose_BC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 40, 40")]
        public global::System.Drawing.Color BtnClose_ILC {
            get {
                return ((global::System.Drawing.Color)(this["BtnClose_ILC"]));
            }
            set {
                this["BtnClose_ILC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59, 59, 59")]
        public global::System.Drawing.Color BtnClose_IFC {
            get {
                return ((global::System.Drawing.Color)(this["BtnClose_IFC"]));
            }
            set {
                this["BtnClose_IFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111, 31, 49")]
        public global::System.Drawing.Color BtnClose_ALC {
            get {
                return ((global::System.Drawing.Color)(this["BtnClose_ALC"]));
            }
            set {
                this["BtnClose_ALC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color FontColor {
            get {
                return ((global::System.Drawing.Color)(this["FontColor"]));
            }
            set {
                this["FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color PanelMenu {
            get {
                return ((global::System.Drawing.Color)(this["PanelMenu"]));
            }
            set {
                this["PanelMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color COPanel {
            get {
                return ((global::System.Drawing.Color)(this["COPanel"]));
            }
            set {
                this["COPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color PanelTheme {
            get {
                return ((global::System.Drawing.Color)(this["PanelTheme"]));
            }
            set {
                this["PanelTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color BtnBackColor {
            get {
                return ((global::System.Drawing.Color)(this["BtnBackColor"]));
            }
            set {
                this["BtnBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("43, 43, 43")]
        public global::System.Drawing.Color panelSepa {
            get {
                return ((global::System.Drawing.Color)(this["panelSepa"]));
            }
            set {
                this["panelSepa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color BtnNormalCo {
            get {
                return ((global::System.Drawing.Color)(this["BtnNormalCo"]));
            }
            set {
                this["BtnNormalCo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 40, 40")]
        public global::System.Drawing.Color BtnActiveCo {
            get {
                return ((global::System.Drawing.Color)(this["BtnActiveCo"]));
            }
            set {
                this["BtnActiveCo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color BtnOnhoverCo {
            get {
                return ((global::System.Drawing.Color)(this["BtnOnhoverCo"]));
            }
            set {
                this["BtnOnhoverCo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color BtnTextCo {
            get {
                return ((global::System.Drawing.Color)(this["BtnTextCo"]));
            }
            set {
                this["BtnTextCo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color BtnOnhoverTextCo {
            get {
                return ((global::System.Drawing.Color)(this["BtnOnhoverTextCo"]));
            }
            set {
                this["BtnOnhoverTextCo"] = value;
            }
        }
    }
}
